### ISSUE TITLE
1.21.5

### ISSUE THREAD

**Issue by Simon16102007** [IntellectualSites/FastAsyncVoxelSniper#418]
### What feature do you want to see added?

![Image](https://github.com/user-attachments/assets/f71ac1cb-effa-4a36-a039-f12fe7d90e6f)

on curseforge it says that it would be the version for 1.21.5, but it doesn't work, so i wanted to ask if there is a version for 1.21.5 yet

### Are there any alternatives?

-

**Comment by PierreSchwang** [comment]
What's the error indicating, that it doesn't work on 1.21.5?

**Comment by Simon16102007** [comment]
[14:39:30 ERROR]: Error occurred while enabling FastAsyncVoxelSniper v3.2.3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.world.block.BlockTypes
	at fastasyncvoxelsniper-3.2.3.jar/com.thevoxelbox.voxelsniper.config.VoxelSniperConfigLoader.<clinit>(VoxelSniperConfigLoader.java:46) ~[fastasyncvoxelsniper-3.2.3.jar:?]
	at fastasyncvoxelsniper-3.2.3.jar/com.thevoxelbox.voxelsniper.VoxelSniperPlugin.loadConfig(VoxelSniperPlugin.java:122) ~[fastasyncvoxelsniper-3.2.3.jar:?]
	at fastasyncvoxelsniper-3.2.3.jar/com.thevoxelbox.voxelsniper.VoxelSniperPlugin.onEnable(VoxelSniperPlugin.java:75) ~[fastasyncvoxelsniper-3.2.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:649) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:741) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:486) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1161) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:308) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.block.BlockTypes.init(BlockTypes.java:2217) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.block.BlockTypes.<clinit>(BlockTypes.java:48) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.block.BlockState.get(BlockState.java:153) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.block.BlockState.get(BlockState.java:129) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:124) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:84) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:329) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:436) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:294) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at FastAsyncWorldEdit-Paper-2.13.0.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:264) ~[FastAsyncWorldEdit-Paper-2.13.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:649) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:236) ~[paper-1.21.5.jar:1.21.5-56-1acf3b3]
	... 3 more
[14:39:30 INFO]: Disabling FastAsyncVoxelSniper v3.2.3

**Comment by PierreSchwang** [comment]
> Could not initialize class com.sk89q.worldedit.world.block.BlockTypes

Indicates that FAWE has an issue starting, which is a dependency for FAVS (which makes FAVS fail to start). Not something that is wrong with FAVS. For support, join the discord.
